[package]
name = "proc-macro-id"
version = "1.0.1"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/proc-macro-id"
description = "Identity procedural macro"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true
